# Generated by Django 6.0.1 on 2026-01-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_lat_order_lng_order_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
