# Generated by Django 6.0.1 on 2026-01-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
