# Generated by Django 6.0.1 on 2026-01-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_order_payment_method'),
        ('shop', '0004_alter_product_options_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma elementi', 'verbose_name_plural': 'Buyurtma elementlari'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=120, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Chegirma (so'm)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta orqali')], default='cash', max_length=10, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Jamoa tokeni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('processing', 'Qayta ishlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('done', 'Tugallandi'), ('canceled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.PositiveIntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='Soni'),
        ),
    ]
